ecommerce2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('money.urls')),
    path('conversation/', include('conversation.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

money/urls.py
from django.urls import path
app_name = 'money'
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("new-item/", views.new_item, name="new-item"),
    path("detail/<pk>/", views.detail, name="detail"),
    path("delete/<int:pk>/", views.delete_view, name="delete"),
    path("edit-item/<int:pk>/", views.edit_item, name="edit"),
    path("search/", views.search,name="search")

]

money/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = "Categories"
        ordering = ["name"]

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name="products", on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    description = models.TextField()

    is_sold = models.BooleanField(default=False)
    stock = models.IntegerField()

    created_by = models.ForeignKey(User, related_name="products", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    image = models.ImageField(upload_to="images")

    def __str__(self):
        return self.name

money/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from .models import Product

class EditProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["category", "name", "price", "description", "is_sold", "stock", "image"]


class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["category", "name", "price", "description", "is_sold", "stock", "image"]


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]

    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Enter Username",
        "class": "form-control"
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Enter Password",
        "class": "form-control"
    }))





class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Enter Username",
        "class": "form-control"
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        "placeholder": "Enter Email",
        "class": "form-control"
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Enter Password",
        "class": "form-control"
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Repeat Password",
        "class": "form-control"
    }))

money/views.py

from django.shortcuts import render, redirect, get_object_or_404
from .models import Product
from .forms import RegisterForm, UserLoginForm, AddProductForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q

# Create your views here.

def search(request):
    query = request.GET.get('query',"")

    products = Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))

    context = {
        'query': query,
        'products':products
    }
    return render(request,'money/search.html',context)



def delete_view(request, pk):
    product = get_object_or_404(Product, pk, created_by=request.user)

    if request.method == "POST":
        product.delete()
        return redirect("money:home")

    context = {
        "product": product,
    }
    return render(request, "money/delete.html", context)


def detail(request, pk):

    product = get_object_or_404(Product, pk=pk)

    related_products = Product.objects.filter(category=product.category).exclude(pk=pk)

    context = {
        "product": product,
        "related_products": related_products,
    }
    return render(request, "money/detail.html", context)




@login_required
def edit_item(request, pk):

    product = get_object_or_404(Product, pk=pk, created_by=request.user)

    form = AddProductForm(instance=product)

    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
        return redirect("money:home")

    context = {
        "form": form,
        "product": product
        }
    return render(request, "money/form.html", context)



@login_required
def new_item(request):
    form = AddProductForm()

    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.created_by = request.user
            product.save()
            return redirect("money:home")

    context = {"form": form}
    return render(request, "money/form.html", context)



def logout_view(request):
    logout(request)
    return redirect("coreApp:login")


def login_view(request):

    if request.method == "POST":
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect("money:home")

    else:
        form = UserLoginForm()

    context = {"form": form}
    return render(request, "money/login.html", context)


def signup(request):

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("money:home")

    else:
        form = RegisterForm()

    context = {"form": form}
    return render(request, "money/signup.html", context)


def home(request):
    products = Product.objects.all()

    context = {"products": products}
    return render(request, "money/home.html", context)

templates/money/base.html
{% load static%}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
           <a class="nav-link active" href="{% url 'money:signup' %}">Signup</a>
        </li>
        <li>
          <a class="nav-link active" href="{% url 'money:login' %}">Login</a>
        </li>
        <li>
          <a class="nav-link active" href="{% url 'money:new-item' %}">Add Product</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><hr class="dropdown-divider"></li>
        </li>
      </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search" action="{% url 'money:search' %}" method="GET">
        <input class="form-control me-2" type="search" placeholder="find items" aria-label="Search" name="query" value="{{ query }}">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
  <div>
    {% block content %}
      <h1> Home Page </h1>
    {% endblock content %}
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/money/delete.html
 {% extends "money/base.html" %}

    {% block title %}Delete{% endblock title %}

    {% block content %}
    <h1>Delete</h1>
        <form action="" method="POST">
            {% csrf_token %}

            <p class="my-5">Are you sure that you want to delete <strong>"{{ product.name }}"</strong>?</p>

            <a href="{% url 'money:detail' product.pk %}" class="btn btn-success">Back</a>
            <button type="submit" class="btn btn-danger">Yes, Delete</button>
        </form>

    {% endblock content %}

templates/money/detail.html
 {% extends 'money/base.html' %}

    {% block title %}{{ product.name }} Detail{% endblock title %}

    {% block content %}

    <h1>{{ product.name }} - Detail Page</h1>

    <div class="card mb-3" style="max-width: 90%;">
      <div class="row g-0">
        <div class="col-md-5">
          <img src="{{ product.image.url }}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-7">
          <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5><br>
            <p class="card-text">${{ product.price }}</p><br>
            <p class="card-text"><strong>Description:</strong><br>{{ product.description }}</p>

            <br>
            <hr>

            {% if request.user == product.created_by %}
              <a href="{% url 'money:edit' product.pk %}" class="btn btn-success">Edit</a>
              <a href="{% url 'money:delete' product.pk %}" class="btn btn-danger">Delete</a>

            {% else %}
              <a href="" class="btn btn-primary">Contact Seller</a>

            {% endif %}

          </div>
        </div>
      </div>
    </div>

    <br>

    <h1>Related Products</h1>

    <div class="row">
      {% if related_products %}
        {% for product in related_products %}
        <div class="col">
            <div class="card" style="width: 18rem;">
              <img src="{{ product.image.url }}" class="card-img-top" alt="..." height="250;" border="2px solid green;">
              <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">${{ product.price }}</p>
                <a href="{% url 'money:detail' product.pk %}" class="btn btn-primary">View</a>
              </div>
            </div>
        </div>

        {% endfor %}
      {% else %}
        <p>There is no related products for this category</p>
      {% endif %}
    </div>
 {% endblock content %}

templates/money/form.html
{% extends "money/base.html" %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
    <h1>{{ title }}</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

templates/money/home.html
{% extends 'money/base.html' %}

{% block content %}
    <h1> Home Page</h1>


<div class="row">
        {% for product in products %}
        <div class="col">
            <div class="card" style="width: 18rem;">
              <img src="{{ product.image.url }}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">${{ product.price }}</p>
                <a href="{% url 'money:detail' product.pk %}" class="btn btn-primary">View</a>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock content %}

templates/money/login.html
{% extends "money/base.html" %}
{% block title %}Login{% endblock title %}
{% block content %}
    <h1>Login</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock content %}

templates/money/newproduct.html
{% extends "money/base.html" %}
{% block title %}New Product{% endblock title %}
{% block content %}
    <h1>Add New Product</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Product</button>
    </form>
{% endblock content %}

templates/money/search.html

{% extends "money/base.html" %}

{% block title %}Search{% endblock title%}

{% block content %}

{% if query%}
    <h1>Find Result for "{{ query }}"</h1>
{% else %}
    <h1>Find Items</h1>
{% endif %}

    <div class="py-5 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <!-- looping over the item -->
                {% if products %}
                    {% for product in products %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="{{ product.image.url }}" alt="" width="100%" height="225">
                            <div class="card-body">
                                <p class="card-text"> {{ product.name }} </p>
                                <p class="card-text">$ {{ product.price }}</p>
                                <p class="card-text">{{ product.description }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{% url 'money:detail' product.id %}" type="button"
                                           class="btn btn-sm btn-outline-secondary">View</a>
                                        <button type="button" class="btn btn-sm btn-outline-secondary">Buy Now</button>
                                        <!-- add to cart and take the user to checkout page-->
                                    </div>
                                    <small class="text-body-secondary">@ {{ product.created_by.username }} </small>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <!-- endfor -->
                {% else %}
                <p>No product was found</p>
                {% endif %}
            </div>
        </div>
    </div>

    {% endblock content %}







templates/money/signup.html
{% extends "money/base.html" %}
{% block title %}Signup{% endblock title %}
{% block content %}
    <h1>Signup</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send</button>
    </form>
{% endblock content %}